[test]
levels = ["syntax", "install", "registration", "instantiation", "static_capture", "execution"]

[test.workflows]
run = "all"
screenshot = "all"
timeout = 300
gpu = "all"

[test.platforms]
linux = true
macos = false #requires cuda
windows = true
windows_portable = true