[test]
levels = ["syntax", "install", "registration", "execution"]

[test.workflows]
run = "all"
screenshot = "all"
timeout = 300
gpu = ["remeshing_gpu.json"]

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true