[cuda]
packages = ["torch-scatter","torch-cluster","spconv","flash-attn"]

[pypi-dependencies]
numpy = "<2.0"
trimesh = { version = "*", extras = ["easy"] }
transformers = "==4.51.3"
pytorch_lightning = "*"
lightning = "*"
timm = "*"
einops = "*"
addict = "*"
omegaconf = "*"
python-box = "*"
huggingface_hub = "*"
wandb = "*"
fast-simplification = "*"
pyrender = "*"
libigl = "*"
cumm = "*"
embreex = "*"
pccm = "*"
shapely = "*"

[target.linux-64.pypi-dependencies]
triton = ">=3.0.0"
